import { expect, test } from "@playwright/test"

const api = "http://127.0.0.1:8799/study-plan"

test("guest records, edits, repeats, and reloads Course Attempts locally", async ({ page }) => {
  await page.clock.setFixedTime(new Date("2026-09-26T12:00:00Z"))
  await page.goto("/planner")
  const completed = page.getByRole("region", { name: "Completed Courses" })
  await expect(page.getByRole("heading", { name: "Intended Courses" })).toBeVisible()
  await completed.getByLabel("Find Course for attempt").fill("6200")
  await completed.getByLabel("Course for attempt", { exact: true }).selectOption("CS-6200")
  await completed.getByLabel("Attempt year").fill("2013")
  await completed.getByLabel("Attempt outcome").selectOption("C")
  await completed.getByRole("button", { name: "Record Course Attempt" }).click()
  const first = completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" })
  await expect(first.getByLabel("Outcome")).toHaveValue("C")
  await first.getByLabel("Outcome").selectOption("B")
  await first.getByLabel("Attempt 1 year").fill("2012")
  await first.getByLabel("Outcome").click()
  await completed.getByLabel("Find Course for attempt").fill("6200")
  await completed.getByLabel("Course for attempt", { exact: true }).selectOption("CS-6200")
  await completed.getByLabel("Attempt season").selectOption("Spring")
  await completed.getByLabel("Attempt year").fill("2021")
  await completed.getByLabel("Attempt outcome").selectOption("A")
  await completed.getByRole("button", { name: "Record Course Attempt" }).click()
  await expect(completed.getByText("2 attempts")).toBeVisible()
  await page.reload()
  await expect(completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" }).getByLabel("Outcome")).toHaveValue("B")
  await expect(completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" }).getByLabel("Attempt 1 year")).toHaveValue("2012")
  await expect(completed.getByRole("listitem", { name: "Attempt 2 for CS-6200" }).getByLabel("Outcome")).toHaveValue("A")
  expect((await (await page.request.get(api, { headers: { authorization: "Bearer fixture:guest-attempt" } })).json()).attempts).toEqual([])
})

test("merge preserves guest and account attempts; owner alone can read or edit", async ({ page }) => {
  const accountAttempt = { id: "00000000-0000-4000-8000-000000000018", courseId: "CS-6200", term: "Fall-2019", outcome: "C" }
  const localAttempt = { id: "00000000-0000-4000-8000-000000000019", courseId: "CS-6200", term: "Spring-2020", outcome: "B" }
  expect((await page.request.put(api, { headers: { authorization: "Bearer fixture:attempt-owner" }, data: { plan: {}, selectedSpec: null, attempts: [accountAttempt], revision: 0 } })).status()).toBe(200)
  await page.addInitScript((attempt) => localStorage.setItem("omscs-hub:attempts:v1", JSON.stringify([attempt])), localAttempt)
  await page.goto("/sign-in?clerk=attempt-owner")
  await page.getByLabel("Email", { exact: true }).fill("student@gatech.edu")
  await page.getByRole("button", { name: "Send code" }).click()
  await page.getByLabel("Email code").fill("123456")
  await page.getByRole("button", { name: "Verify code" }).click()
  await page.getByRole("link", { name: "Review plans" }).click()
  const panel = page.getByRole("region", { name: "Choose Study Plan sync" })
  await expect(panel).toContainText("Fall-2019")
  await expect(panel).toContainText("Spring-2020")
  await panel.getByRole("button", { name: "Merge plans" }).click()
  await expect(page.getByText("Study Plan saved to your private account.")).toBeVisible()
  const completed = page.getByRole("region", { name: "Completed Courses" })
  await expect(completed.getByText("2 attempts")).toBeVisible()
  const first = completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" })
  await first.getByLabel("Outcome").selectOption("A")
  await expect(page.getByText("Study Plan saved to your private account.")).toBeVisible()
  await page.reload()
  await expect(completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" }).getByLabel("Outcome")).toHaveValue("A")
  const owner = await (await page.request.get(api, { headers: { authorization: "Bearer fixture:attempt-owner" } })).json()
  expect(owner.attempts).toHaveLength(2)
  expect(owner.attempts[0].outcome).toBe("A")
  expect((await page.request.get(api)).status()).toBe(401)
  expect((await (await page.request.get(api, { headers: { authorization: "Bearer fixture:other-owner" } })).json()).attempts).toEqual([])
  expect((await page.request.put(api, { headers: { authorization: "Bearer fixture:other-owner" }, data: { ...owner, attempts: [], revision: owner.revision } })).status()).toBe(409)
})

test("failed attempt sync survives reload and saves after retry", async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem("clerk-fixture-session", "active")
    localStorage.setItem("clerk-fixture-scenario", "attempt-retry")
  })
  await page.goto("/planner")
  await expect(page.getByText("Study Plan saved to your private account.")).toBeVisible()
  await page.route(api, (route) => route.request().method() === "PUT" ? route.abort() : route.continue())
  const completed = page.getByRole("region", { name: "Completed Courses" })
  await completed.getByLabel("Find Course for attempt").fill("6200")
  await completed.getByLabel("Course for attempt", { exact: true }).selectOption("CS-6200")
  await completed.getByLabel("Attempt outcome").selectOption("F")
  await completed.getByRole("button", { name: "Record Course Attempt" }).click()
  await expect(page.getByRole("button", { name: "Retry sync" })).toBeVisible()
  await page.reload()
  await expect(completed.getByRole("listitem", { name: "Attempt 1 for CS-6200" }).getByLabel("Outcome")).toHaveValue("F")
  await page.unroute(api)
  await page.getByRole("button", { name: "Retry sync" }).click()
  await expect(page.getByText("Study Plan saved to your private account.")).toBeVisible()
  const saved = await (await page.request.get(api, { headers: { authorization: "Bearer fixture:attempt-retry" } })).json()
  expect(saved.attempts).toHaveLength(1)
  expect(saved.attempts[0].outcome).toBe("F")
})
